-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  USING (CAR_TYPE)
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
    WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
) 
AND (CAR_TYPE = "세단" OR CAR_TYPE = "SUV")
AND DURATION_TYPE LIKE "30%"
AND ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;