-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK_SALES
NATURAL JOIN BOOK
NATURAL JOIN AUTHOR
WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;