-- 코드를 입력하세요
/*
SELECT CAR_ID, CASE
    WHEN EXISTS (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
        WHERE c1.CAR_ID = c2.CAR_ID AND (c2.START_DATE <= "2022-10-16" AND c2.END_DATE >= "2022-10-16")
    ) THEN "대여중"
    ELSE "대여 가능"
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c1
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
*/

SELECT CAR_ID, CASE
    WHEN EXISTS (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
        WHERE c1.CAR_ID = c2.CAR_ID AND ("2022-10-16" BETWEEN c2.START_DATE AND c2.END_DATE)
    ) THEN "대여중"
    ELSE "대여 가능"
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c1
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;