-- 코드를 입력하세요
SELECT HISTORY_ID, CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN ROUND((
        SELECT (100 - DISCOUNT_RATE) / 100 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cdp
        WHERE TRUCK_INFO.CAR_TYPE = cdp.CAR_TYPE
            AND DURATION_TYPE LIKE "90%"
    ) * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN ROUND((
        SELECT (100 - DISCOUNT_RATE) / 100 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cdp
        WHERE TRUCK_INFO.CAR_TYPE = cdp.CAR_TYPE
            AND DURATION_TYPE LIKE "30%"
    ) * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN ROUND((
        SELECT (100 - DISCOUNT_RATE) / 100 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cdp
        WHERE TRUCK_INFO.CAR_TYPE = cdp.CAR_TYPE
            AND DURATION_TYPE LIKE "7%"
    ) * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))
    ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
    END AS FEE
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    LEFT JOIN CAR_RENTAL_COMPANY_CAR USING (CAR_ID)
    WHERE CAR_TYPE = "트럭"   
    ) AS TRUCK_INFO
ORDER BY FEE DESC, HISTORY_ID DESC;