-- 코드를 입력하세요
SELECT
    USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM
    USED_GOODS_BOARD AS b LEFT JOIN USED_GOODS_USER AS u
    ON u.USER_ID = b.WRITER_ID
WHERE
    STATUS LIKE "DONE"
GROUP BY
    WRITER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES;
