-- 코드를 입력하세요
SELECT a.APNT_NO, PT_NAME, p.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
NATURAL JOIN PATIENT p
INNER JOIN DOCTOR d ON MDDR_ID = DR_ID
WHERE (APNT_CNCL_YN = "N" OR APNT_CNCL_YN IS NULL)
    AND DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND a.MCDP_CD = "CS"
ORDER BY APNT_YMD;