-- 코드를 입력하세요
SELECT 
    TITLE, BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM
    USED_GOODS_BOARD AS b
    RIGHT JOIN USED_GOODS_REPLY AS r
    USING (BOARD_ID)
WHERE
    YEAR(b.CREATED_DATE) = 2022
    AND MONTH(b.CREATED_DATE) = 10
ORDER BY
    r.CREATED_DATE,
    TITLE;